egrep:
  keywords:
    - something
  options: -iran
  regex: '\.{key}|\.try\(.*:{key}|\.try\!\(.*:{key}'
  exclusions:
    directories:
      - spec
      - tmp
      - .git
      - db
      - virtualbox_sidekiq_test
      - log
      - public
      - vendor
    files:
      - webpack_admin.js
  targetDir: ./
  output:
    excel:
      filePath: 'EgrepResults.xlsx'
      sheet:
        nameLimit: 31