egrep:
  keywords:
    - main
    - excel
    - Directories
  options: -iran
  regex: '\.{key}'
  exclusions:
    directories:
      - public
      - spec
    files:
      - .gitignore
  targetDir: ./
  output: 'test.xlsx'